"""updaing Task and Repo

Revision ID: 821bb98c7936
Revises: cbfb6071642c
Create Date: 2025-12-31 14:58:31.633461

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "821bb98c7936"
down_revision: Union[str, Sequence[str], None] = "cbfb6071642c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("task", sa.Column("owner", sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("task", "owner")
    # ### end Alembic commands ###
