"""adding webhook_secret column to repo table

Revision ID: cbfb6071642c
Revises: edc23f3b4247
Create Date: 2025-12-30 19:17:09.831051

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbfb6071642c'
down_revision: Union[str, Sequence[str], None] = 'edc23f3b4247'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('repo', sa.Column('webhook_secret', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('repo', 'webhook_secret')
    # ### end Alembic commands ###
