"""adding repo table --fix

Revision ID: edc23f3b4247
Revises: c4758e9dc3a5
Create Date: 2025-12-30 19:08:53.299989

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edc23f3b4247'
down_revision: Union[str, Sequence[str], None] = 'c4758e9dc3a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('repo',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('repo_name', sa.String(), nullable=False),
    sa.Column('installation_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_repo_name'), 'repo', ['repo_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_repo_repo_name'), table_name='repo')
    op.drop_table('repo')
    # ### end Alembic commands ###
